export default {
  DEPOSIT: 2,
  TRANSFER: 3,
  CONSOLIDATE: 4,
  COMP_REQ: 5,
  COMP_RESP: 6,
  EXIT: 7,
  VALIDATOR_JOIN: 8,
  VALIDATOR_LOGOUT: 9,
  // 10 was for VALIDATOR_LEAVE
  PERIOD_VOTE: 11,
};
