name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - run: npm install
    - name: lint
      run: npm run lint
    - name: tests
      run: ./node_modules/.bin/nyc --reporter=lcov npm test
    - name: upload coverage report
      uses: codecov/codecov-action@v1.0.5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

